version: '3.8'

services:
  # --- Service 1: The Database ---
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: retail_db
    environment:
      - ORACLE_PASSWORD=AdminPassword123
      - ORACLE_DATABASE=xepdb1
    ports:
      - "1521:1521"
    volumes:
      # 1. Input Data (Already there)
      - ./data:/data
      # 2. NEW: Persist Database Files (Users, Tables, Data)
      - oracle_data:/opt/oracle/oradata
    networks:
      - etl-network
    restart: unless-stopped

  # --- Service 2: Jenkins ---
  jenkins:
    build: .
    container_name: retail_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./data:/data
      - .:/project
    networks:
      - etl-network
    depends_on:
      - oracle-db

# --- Define the Volume ---
volumes:
  oracle_data:
    driver: local

networks:
  etl-network:
    driver: bridge